<?php

namespace Attend;


class ClassroomsRepository extends Repository
{
    public static function getTableName()
    {
        return 'classrooms';
    }

    public static function getColumnNames()
    {
        return [
            'id'         => [
                'insert' => false,
                'update' => false,
                'select' => true
            ],
            'label'      => [
                'insert' => true,
                'update' => true,
                'select' => true
            ],
            'ordering'   => [
                'insert' => true,
                'update' => true,
                'select' => true
            ],
            'created_at' => [
                'insert' => false,
                'update' => false,
                'select' => true
            ],
            'updated_at' => [
                'insert' => false,
                'update' => false,
                'select' => true
            ]
        ];
    }

    public function insert($parsedBody)
    {
        if (array_key_exists('ordering', $parsedBody) && ('' == $parsedBody[ 'ordering' ])) {
            $parsedBody[ 'ordering' ] = null;

        } else if (isset($parsedBody[ 'ordering' ])) {
            $sql = 'UPDATE classrooms SET ordering = ordering + 1 where ordering >= ?';
            $sth = $this->getPdo()->prepare($sql);
            $sth->execute([$parsedBody[ 'ordering' ]]);
        }

        return parent::insert($parsedBody); // TODO: Change the autogenerated stub
    }


}
